In [2]:
import numpy as np

x = np.array([[1],[3],[4]])
#print(x.shape)
#np.repeat(x, 2)
#print(x)

#degree = 2

n,d1 = x.shape
degree = 3
update = np.zeros((n,degree))
print(update)
for i in range(n):
    #print(f'i = {i} and value is {x[i]}')
    for j in range(degree):
        #print (f'j = {j} and value is {x[i] ** (j+1)}')
        update[i,j] = x[i] ** (j+1)
        #np.put(update, (i,j), v )

print(update)


#np.tile(x, (1, 2))

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[ 1.  1.  1.]
 [ 3.  9. 27.]
 [ 4. 16. 64.]]


In [3]:
def polyfeatures(X: np.ndarray, degree: int) -> np.ndarray:
        """
        Expands the given X into an (n, degree) array of polynomial features of degree degree.

        Args:
            X (np.ndarray): Array of shape (n, 1).
            degree (int): Positive integer defining maximum power to include.

        Returns:
            np.ndarray: A (n, degree) numpy array, with each row comprising of
                X, X * X, X ** 3, ... up to the degree^th power of X.
                Note that the returned matrix will not include the zero-th power.

        """
        n, d1 = X.shape
        if degree < 1:
            pfX_ = np.zeros((1, 1))
        else:
            if d1 != 1:
                pfX_ = np.zeros((1, 1))
            else:
                pfX_ = np.zeros((n, degree))
                for i in range(n):
                    for j in range(degree):
                        pfX_[i, j] = X[i] ** (j + 1)
        return pfX_

In [6]:
x = np.array([[1],[2],[3]])
print(x.shape)
print(x)

a = polyfeatures(x, 5)
print(a)
XNormed = (a - np.mean(a, axis = 0))/(np.std(a, axis = 0))
print(XNormed)

n1,d1 = XNormed.shape
newdata = np.zeros((n1, d1+1))
newdata[:,0] = 1
print(newdata)

for i in range(n1):
    for j in range(d1):
        newdata[i, j+1] = XNormed[i,j]
#print(XNormed)

print(f'via loop is \n {newdata}')

#print(polyfeatures(x, 5))

X_ = np.c_[np.ones([n1, 1]), XNormed]
print(f'via new stuff is \n {X_}')


(3, 1)
[[1]
 [2]
 [3]]
[[  1.   1.   1.   1.   1.]
 [  2.   4.   8.  16.  32.]
 [  3.   9.  27.  81. 243.]]
[[-1.22474487 -1.1111678  -1.00138026 -0.91202919 -0.84634991]
 [ 0.         -0.20203051 -0.36413828 -0.48001536 -0.55803291]
 [ 1.22474487  1.31319831  1.36551854  1.39204455  1.40438282]]
[[1. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0.]]
via loop is 
 [[ 1.         -1.22474487 -1.1111678  -1.00138026 -0.91202919 -0.84634991]
 [ 1.          0.         -0.20203051 -0.36413828 -0.48001536 -0.55803291]
 [ 1.          1.22474487  1.31319831  1.36551854  1.39204455  1.40438282]]
via new stuff is 
 [[ 1.         -1.22474487 -1.1111678  -1.00138026 -0.91202919 -0.84634991]
 [ 1.          0.         -0.20203051 -0.36413828 -0.48001536 -0.55803291]
 [ 1.          1.22474487  1.31319831  1.36551854  1.39204455  1.40438282]]


In [4]:
def mean_squared_error(a: np.ndarray, b: np.ndarray) -> float:
    """Given two arrays: a and b, both of shape (n, 1) calculate a mean squared error.

    Args:
        a (np.ndarray): Array of shape (n, 1)
        b (np.ndarray): Array of shape (n, 1)

    Returns:
        float: mean squared error between a and b.
    """
    #return (np.square(a - b)).mean(axis=None)
    if a.shape != b.shape:
        return -1
    else:
        return np.square(np.subtract(a, b)).mean()



In [ ]:
from typing import Callable
from unittest import TestCase, TestLoader, TestSuite

import numpy as np
from gradescope_utils.autograder_utils.decorators import partial_credit, visibility

from homeworks.poly_regression.polyreg import (
    PolynomialRegression,
    learningCurve,
    mean_squared_error,
)

degree = 3
reg_lambda = 0
X = np.linspace(-1, 1, 10).reshape(-1, 1)
y = X ** 3
X_test = np.linspace(0, 4, 10).reshape(-1, 1)

expected = X_test ** 3

model = PolynomialRegression(degree=degree, reg_lambda=reg_lambda)
model.fit(X, y)
actual = model.predict(X_test)

print (f'actual is \n  {actual}')
print (f'expected is \n  {expected}')