In [3]:
from typing import Optional, Tuple

import matplotlib.pyplot as plt
import numpy as np

from utils import problem


def random_data_generator(n, d, k, mean, variance ) -> Tuple[np.ndarray, np.ndarray]:
    """Generates random data sets for X and y based on the dimensions and noise

    Args:
        n: number of rows of X
        d: number of features of X
        k: number of relevant features of X
        mean: mean of the noise term
        variance: variance of the noise term

    Returns:
        Tuple[np.ndarray, np.ndarray]: Tuple with 2 entries. First represents input X, second represents predictions y

    """
    w = np.zeros((d, 1))

    for j in range(k) :
        w[j] = (j + 1) / k

    X = np.random.normal(size=(n, d))
    noise = np.random.normal(scale=np.sqrt(variance), size=(n,))

    y = np.reshape(np.dot(w.T, X.T) + noise.T, (n,))

    return (X, y)


In [4]:
X, y = random_data_generator(500, 1000, 100, 0, 1)

print(f'X is : \n {X}')
print(f'y is : \n {y}')

X is : 
 [[-0.60279325 -0.28472629 -0.81010165 ...  2.07265795  0.52317931
   0.29377696]
 [ 0.75612101 -0.45161942 -1.79052593 ...  1.41640693 -0.53195782
   0.06707871]
 [-0.46674179  1.63038384  2.07144879 ... -1.7550755  -0.67670019
   1.0098044 ]
 ...
 [-1.0621924   1.78893417  1.15941691 ... -0.72775207  0.16694695
  -0.96769079]
 [ 0.06126637  0.19628196 -0.72640275 ... -1.36906881  0.01233223
   0.98638017]
 [ 1.59321388 -0.49260511  0.60317294 ...  0.69599951 -1.88234683
  -0.09747067]]
y is : 
 [ 3.58976305e+00  6.05826321e+00 -2.87173806e+00  1.11613924e+00
 -1.98331229e+00  7.50251064e+00  1.86531032e+00 -1.71596767e-01
 -3.73057205e+00  3.15322917e-01  2.30789296e+00 -5.90547192e+00
  4.38354209e+00  2.32275619e-01  9.63644070e+00 -2.06408725e-01
 -1.89950290e+00  9.75759583e+00  7.46277230e+00 -3.58382660e+00
  8.23846006e+00  2.92245366e+00 -8.30850911e+00  1.81871273e+00
 -5.53682061e+00  6.13281053e+00 -2.92213021e+00  4.91177212e+00
  6.40822046e+00  4.91458219e+00 -2

In [30]:
X_1 = X[1,1:5]
print(X_1)
Y_1 = y[1:5]
print(Y_1)

print(abs((np.subtract(X_1, Y_1))))
diff = abs((np.subtract(X_1, Y_1)))
print(f'Diff is {diff}')


#print(np.any(diff > 0.1))

print(np.any(abs((np.subtract(X_1, Y_1))) > 0.1))



[-0.45161942 -1.79052593  0.46676623 -2.17974259]
[ 6.05826321 -2.87173806  1.11613924 -1.98331229]
[6.50988263 1.08121212 0.64937301 0.1964303 ]
Diff is [6.50988263 1.08121212 0.64937301 0.1964303 ]
True


In [37]:
start_weight = np.zeros(5)

print(start_weight)
old_w: Optional[np.ndarray] = None

if(old_w == None):
    print("None array")
else:
    print("not none")

#print(np.any(abs((np.subtract(start_weight, old_w))) > 50))

print(np.count_nonzero(start_weight))



[0. 0. 0. 0. 0.]
None array
0


In [38]:
if start_weight is None:
        start_weight = np.zeros(X.shape[1])
        start_bias = 0
    old_w: Optional[np.ndarray] = None
    old_b: Optional[np.ndarray] = None
    _lambda_values = []
    num_non_zeros = []
    i = 0
    while not convergence_criterion(start_weight, old_w, start_bias, old_b, convergence_delta):
        _lambda_values[i] = _lambda
        num_non_zeros[i] = np.count_nonzero(start_weight)
        old_w = start_weight.copy()
        old_b = start_bias.copy()
        start_weight, start_bias = step(X, y, start_weight, start_bias, _lambda, eta)

        _lambda = _lambda / 2
        i += 1

    return (start_weight, start_bias)
